### ISSUE TITLE
Cannot login after deleting a workspace

### ISSUE THREAD

**Issue by vparekh94** [astronomer/houston-api#50]
After deleting a workspace, I am unable to log into the platform with the user I was previously logged in as.

Steps to recreate:

1) Login

2) Create a workspace

3) Delete that workspace

Houston Logs:
```
(node:3609) UnhandledPromiseRejectionWarning: Error: Variable '$where' expected value of type 'DeploymentWhereInput' but got: {"workspace":{"id_in":["cju5uvywv000y0b13afbwmdhw","cju8fwp3300qz0b132lkcz1ra","cjueoz99v01as0c57zz485b0t",null]}}. Reason: 'workspace.id_in[0]' String or Int value expected (line 1, column 8):
query ($where: DeploymentWhereInput) {
       ^
    at BatchedGraphQLClient.<anonymous> (/houston/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/houston/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/houston/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/houston/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

Console page of webpage:

![image](https://user-images.githubusercontent.com/19679395/56511504-c159cc00-64fa-11e9-9473-8663250c49b8.png)

**Comment by schnie** [comment]
Closed with https://github.com/astronomer/houston-api/pull/46. Thanks @ashb, just in time!
