### ISSUE TITLE
Invite users without email confirmation

### ISSUE THREAD

**Issue by vparekh94** [astronomer/houston-api#64]
For users that are running Astronomer Enterprise in clusters without external internet access, they should have the ability to add users without needing email confirmation (or public sign-ups).

This should probably be a flag in helm that gets set upon deployment.

**Comment by ryw** [comment]
@vparekh94 can you reproduce this, confirm that the `emailConfirmation` flag isn't working? looked at code w/ @schnie and this should work https://github.com/astronomer/houston-api/blob/f67be5c96b9382dfffa0267107feada3c4f3bf54/src/lib/users/index.js#L52

**Comment by vparekh94** [comment]
UI:

![image](https://user-images.githubusercontent.com/19679395/58599856-0d153900-8250-11e9-8931-56842ba60aa0.png)


_after inviting user_ 

Houston logs:

```
Type "Node" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
2019-05-30T00:20:24 INFO Server ready at http://localhost:8871/v1
2019-05-30T00:20:24 INFO Subscriptions ready at ws://localhost:8871/ws
2019-05-30T00:20:30 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 9.757 ms
2019-05-30T00:20:33 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.623 ms
2019-05-30T00:20:40 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.684 ms
2019-05-30T00:20:43 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.370 ms
2019-05-30T00:20:50 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.371 ms
2019-05-30T00:20:53 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.381 ms
2019-05-30T00:21:00 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 1.884 ms
2019-05-30T00:21:03 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.328 ms
2019-05-30T00:21:10 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.317 ms
2019-05-30T00:21:13 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.334 ms
2019-05-30T00:21:20 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.364 ms
2019-05-30T00:21:23 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.350 ms
2019-05-30T00:21:30 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.528 ms
2019-05-30T00:21:33 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.602 ms
2019-05-30T00:21:40 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.511 ms
2019-05-30T00:21:43 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.312 ms
2019-05-30T00:21:50 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.568 ms
2019-05-30T00:21:53 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.351 ms
2019-05-30T00:21:55 DEBUG ::ffff:10.28.79.47 - OPTIONS /v1 HTTP/1.1 204 0 - 4.792 ms
2019-05-30T00:21:56 DEBUG Skipping user-invite email to vmpvmp94@gmail.com
2019-05-30T00:21:56 DEBUG ::ffff:10.28.79.47 - POST /v1 HTTP/1.1 200 1250 - 1418.397 ms
```

config.yaml:

```
global:
  acme: false
  baseDomain: demo.datarouter.ai
  tlsSecret: astronomer-tls
grafana:
  resources: {}
nginx:
  loadBalancerIP: 35.245.251.186
  loadBalancerSourceRanges: null
  resources: {}
prometheus:
  resources: {}
astronomer:
  houston:
    config:
      email:
        enabled: False
      emailConfirmation: false
```
https://github.com/astronomer/houston-api/blob/master/config/default.yaml#L149
(assuming this is the right level for that flag)



houston logs:
```
(node:29) UnhandledPromiseRejectionWarning: Error: Public signups are disabled, a valid inviteToken is required
    at createUser (/houston/dist/lib/users/index.js:51:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-05-30T00:25:30 DEBUG ::ffff:10.150.0.115 - GET /v1/healthz HTTP/1.1 200 2 - 0.469 ms

```

In my browser, I'm caught in a redirect loop.

I don't want to turn public sign-on on

**Comment by schnie** [comment]
@vparekh94 when do you get the `Error: Public signups are disabled, a valid inviteToken is required` exception to get thrown?

**Comment by vparekh94** [comment]
When I try to sign in as the user I invited
